In [12]:
import numpy as np

belief_context = np.random.random(2)
belief_context /= belief_context.sum()

belief_location = np.random.random(4)
belief_location /= belief_location.sum()

belief_locinfo = np.random.random(5)
belief_locinfo /= belief_locinfo.sum()

transition_context_location_locinfo = np.random.random((2, 4, 5))
sum_trans = transition_context_location_locinfo.sum(axis=-1)
transition_context_location_locinfo /= sum_trans[:, :, np.newaxis]

belief_locinfo_given_current_belief_loc_for_each_context = belief_location@transition_context_location_locinfo
belief_locinfo_given_current_belief_loc_for_each_context


array([[0.37423033, 0.09746885, 0.23156465, 0.17274765, 0.12398852],
       [0.10939403, 0.23996222, 0.19866242, 0.19006186, 0.26191948]])

In [13]:
belief_locinfo_given_current_belief_loc_for_each_context.sum(axis=-1)

array([1., 1.])

In [17]:
p_context_given_current_belief_locinfo = belief_locinfo@(belief_location@transition_context_location_locinfo).T * belief_context
p_context_given_current_belief_locinfo /= p_context_given_current_belief_locinfo.sum()
p_context_given_current_belief_locinfo

array([0.15713195, 0.84286805])